### ISSUE TITLE
Please add textures

### ISSUE THREAD

**Issue by MidnightPhantom** [thecow275/electrica#5]
Please add textures to the mod

**Comment by thecow275** [comment]
missing following textures

Darkness Plant texture files

- [ ] electrica_darkness_seed.png
- [ ] electrica_darkness.png
- [ ] electrica_darkness_1.png
- [ ] electrica_darkness_2.png
- [ ] electrica_darkness_3.png


Gearbox textures
- [ ] electrica_gearbox_wooden_top.png
- [ ] electrica_gearbox_wooden_bottom.png
- [ ] electrica_gearbox_wooden_side.png
- [ ] electrica_gearbox_iron_side.png

Miscellaneous
- [ ] electrica_testnode.png <-- need to remove subset testing location and make it what it is supposed to be
- [ ] electrica_plastic_plastic_ingot.png
- [ ] bucket_plastic_new <-- need to change to follow electrica_ naming scheme while adding

**Comment by thecow275** [comment]
change following textures

- [ ] all liquid textures related to liguid silicon(e)
- [ ] textures of electrica:ep_silicon_node <- deprecate ep_ items and nodes and make into electrica_ equivalent

changes to gearboxes

- [ ] make gearbox textures change the base texture behind the gear instead of the gear texture color

**Comment by thecow275** [comment]
Closing issue  since large parts of the mod are going through rework no ETA for fixed release yet
